---
apiVersion: machine.openshift.io/v1beta1
kind: Machine
metadata:
  generateName: powervs-actuator-testing-machine-
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: powervs-actuator-k8s
spec:
  providerSpec:
    value:
      apiVersion: machine.openshift.io/v1
      kind: PowerVSMachineProviderConfig
      serviceInstance:
        type: ID
        id: e449d86e-c3a0-4c07-959e-8557fdf55482
      image:
        type: Name
        name: rhcos-49-84-202108041519-0
      network:
        type: Name
        name: pvs-ipi-net
      systemType: s922
      processorType: shared
      processors: "0.25"
      memoryGiB: 8
      keyPairName: karthik-ssh
      userDataSecret:
        name: worker-user-data
      credentialsSecret:
        name: powervs-credentials
