---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: local-powervs-machineset
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: powervs-k8s-cluster
spec:
  replicas: 2
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-machineset: test-master
      machine.openshift.io/cluster-api-cluster: powervs-k8s-cluster
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-machineset: test-master
        machine.openshift.io/cluster-api-cluster: powervs-k8s-cluster
    spec:
      providerSpec:
        value:
          apiVersion: machine.openshift.io/v1
          kind: PowerVSMachineProviderConfig
          serviceInstance:
            type: ID
            id: e449d86e-c3a0-4c07-959e-8557fdf55482
          image:
            type: Name
            name: rhcos-49-84-202108041519-0
          network:
            type: Name
            name: pvs-ipi-net
          systemType: s922
          processorType: shared
          processors: "0.25"
          memoryGiB: 8
          keyPairName: karthik-ssh
          userDataSecret:
            name: worker-user-data
          credentialsSecret:
            name: powervs-credentials
